project:
  type: website
  output-dir: docs

website:
  title: "Shunji Shimoyoshi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - photography.qmd
      - resume.qmd

format:
  html:
    theme:
      - lumen
      - styles.scss
    mainfont: Gelasio
    toc: true
    page-layout: full



