project:
  type: website
  output-dir: docs

website:
  title: "Shunji Shimoyoshi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - photography.qmd
      - resume.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    page-layout: full



